# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'

target 'SaveMyBike' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SaveMyBike


  pod 'AppAuth'

  pod 'SSZipArchive'

  pod 'GoogleMaps'
  pod 'GooglePlaces'

  pod 'Firebase/Core', '5.4.0'
  pod 'Firebase/Messaging', '5.4.0'

end
